### ISSUE TITLE
Move 'ruby-vobject' gem to just 'vobject'

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/ruby-vobject#11]
Strange that the gem name is 'ruby-object' -- should just have been 'vobject'.

----

**TODO**

- [x] Rename gem to `vobject` (d185c2825a65d3c11c1b62e0ce300ee36ac3b27f)
- [x] Add a gem post-install message which notifies users about gem rename, and release it as a new patch version `x.y.99` of `ruby-vobject` (released [1.0.99](https://rubygems.org/gems/ruby-vobject/versions/1.0.99))
- [x] Do a minor version bump on `vobject` gem to make room for `x.y.99` tag (released [1.1.0](https://rubygems.org/gems/vobject/versions/1.1.0))

**Comment by skalee** [comment]
I'm not sure if this is any important in case of this particular gem, as it insn't widely used by others (it has only 1,754 downloads under its previous name). But I want to suggest that typically when a gem is renamed, that there should be a final release under its old name with upgrade notice in a post-install message. Also typically it's a major or minor version bump.

**Comment by ronaldtse** [comment]
@skalee Agreed. Would you be able to help perform this? Thanks!

**Comment by skalee** [comment]
Ok.

**Comment by skalee** [comment]
@ronaldtse 

> You do not have permission to push to this gem. Ask an owner to add you with: gem owner ruby-vobject --add skalee@gmail.com

Or you can push it yourself, it's at tag [v1.0.99](https://github.com/riboseinc/ruby-vobject/tree/v1.0.99).

**Comment by ronaldtse** [comment]
Added. Please help push the gems. Thanks @skalee !

**Comment by skalee** [comment]
Done!

**Comment by ronaldtse** [comment]
Thanks @skalee !
